### ISSUE TITLE
Failed to download dataset

### ISSUE THREAD

**Issue by badieah** [tongbao96/code-for-SFR-AS#2]
Hello, i tried to download the structural function recognition dataset from the link you provided (https://doi.org/10.5281/zenodo.13772003). i got "Error Resolving DOI). Would appreciate it if you can fix it. thanks
<img width="521" alt="image" src="https://github.com/user-attachments/assets/e2c689d4-6494-4206-a9cd-62e472e111d8">

**Comment by tongbao96** [comment]
Hello, I just tested the download link, and it works. Based on the picture you provided, it seems to be a connection timeout issue with the original server. I'm not sure if the Zenodo server was down when you tried to connect. You might need to check your local network or try connecting Zenodo again later.
